### ISSUE TITLE
Custom save path + torrent identifier 

### ISSUE THREAD

**Issue by firesalp** [kleiram/transmission-php#22]
Hi!
As I said, i will probably come back. :)

I used torrentflux-ng until now, but he became very heavy and i had to do some hacks to integrate SSO, etc...  so... I decided to create my own. And is made possible thanks to you :)

I have a few questions:
1)
Is there any way to set a custom save path when adding a torrent? I'm creating a multi user interface, and every user has his own storage space. 

2)
I store user (id) and torrent (hash) into a database, but i realized that torrent must be added firstly to get the hash info. Is there a way to generate hash info (or id) before adding it into transmission? I saw that's not md5 or sha1.

Thanks a lot :+1:

**Comment by sagar3506** [comment]
how to get Hash from magnet  using this lib...  ? just like upper example with .torrent file
