### ISSUE TITLE
PHPUnit fails to include Mock/Model.php

### ISSUE THREAD

**Issue by Kausheel** [kleiram/transmission-php#41]
PHP Fatal error:  Class 'Transmission\Mock\Model' not found in /var/www/test_transmission/vendor/kleiram/transmission-php/tests/Transmission/Tests/Util/PropertyMapperTest.php on line 23

However, if I modify PropertyMapperTest.php and add the following line:

include "/var/www/test_transmission/vendor/kleiram/transmission-php/tests/Transmission/Mock/Model.php";

then everything works fine, all the tests pass. Is this an issue for anyone else, or am I doing something wrong?

**Comment by kleiram** [comment]
I presume you are actually using Composer, yeah?

**Comment by Kausheel** [comment]
Yeah I'm using Composer.

Here's what I'm doing:

1) cd /var/www/test_transmission/vendor/kleiram/transmission-php

2) ../../bin/phpunit --bootstrap phpunit.xml.dist

This runs fine when I include() the Mock\Model file manually to the PropertyMapperTest.php file.

**Comment by kleiram** [comment]
Oh, that's a weird one...I'll look into that!

**Comment by chellem** [comment]
@Kausheel when you run phpunit without any option, it will take phpunit.xml.dist configuration by default and if you need to specify the configuration, you can run it with the option -c like:

```
phpunit -c phpunit.xml.dist".
```

When using the bootstrap option, the file need to be a PHP file not XML, in your case you need to run like so:
```
phpunit --tests/bootstrap.php
```
Regards,
Chellem
