### ISSUE TITLE
Question on getting stats from Stats.php

### ISSUE THREAD

**Issue by toninog** [kleiram/transmission-php#49]
hi

This is not really an issue - just a question around how do I get :: 
getDownloadedBytes() and getUploadedBytes() from Transmission/Model/Stats/Stats.php

Apologies - I am still learning OO PHP :)

Thanks

**Comment by kleiram** [comment]
No problem!

You can get the stats of the session using the following method:

```php
$stats = $transmission->getSessionStats();

$uploaded   = $stats->getUploadedBytes();
$downloaded = $stats->getDownloadedBytes();
```

**Comment by ghost** [comment]
Does this only give you current session statistics? I'd like to get total statistics as well
