### ISSUE TITLE
i have an issue i can use transmission-php

### ISSUE THREAD

**Issue by yas9999** [kleiram/transmission-php#50]
Hello,
please i need your help, i had sent you a message & you replied :Yeah, sure. If you create a issue with the error/exception I can take a look.

please check this: https://www.dropbox.com/s/q213dzi6q824idv/Tutomakers.docx?dl=0

**Comment by kleiram** [comment]
The error shown there indicates that Transmission is either not running, not listening on that host, not listening on that interface or not listening on that port. Make sure you use the correct host/port and make sure you configured Transmission correctly (Google for "transmission rpc", there'll probably be some hits that can help you).

**Comment by yas9999** [comment]
Thank you @kleiram for information, one more thing i need it please.
- there is a way to chose a specific file in order to be downloaded alone ?

best regards,

**Comment by kleiram** [comment]
It is supported using the official Transmission API but the functionality is not yet implemented in this library. I'll create a ticket for this!
