### ISSUE TITLE
[Help] stream files with transmission !

### ISSUE THREAD

**Issue by yas9999** [kleiram/transmission-php#51]
Hello,
can we stream the file instead of downloading it ?
if yes can you please link me to something or commands i need to use

Best regards

**Comment by kleiram** [comment]
Transmission does not support this (as far as I know). But you can look into something like [Peerflix](https://github.com/mafintosh/peerflix).

Also, since this is a library for interacting with the Transmission API, which is meant for managing Transmission I don't think it will be supported.

**Comment by yas9999** [comment]
Thank you so much kleiram :+1: 
i did noticed those days Peerflix, it's from there i got the idea :)

Best regards,
