### ISSUE TITLE
Call to undefined method PropertyAccess::getPropertyAccessor()

### ISSUE THREAD

**Issue by phuong17889** [kleiram/transmission-php#54]
~~~~
Call to undefined method Symfony\Component\PropertyAccess\PropertyAccess::getPropertyAccessor()
~~~~
I saw http://symfony.com/doc/current/components/property_access/introduction.html hasn't any method which is same name.

**Comment by ibrahimch** [comment]
How you solve this ?

**Comment by phuongdev89** [comment]
@ibrahimch see here:
https://github.com/kleiram/transmission-php/commit/320b48ae5b2fdd83cd1f81bf823bc734980adba4
