### ISSUE TITLE
Downloading a torrent to a specific directory

### ISSUE THREAD

**Issue by milankragujevic** [kleiram/transmission-php#60]
I would like each torrent to download to it's own directory, for example :

```
  /mnt/Storage_4TB_0/torrents/[torrent's own infoHash]/
```

How would I accomplish this?

I'm sorry if this has already been asked, I searched through the issues but couldn't find it.

Thanks

**Comment by Kausheel** [comment]
This functionality has already been merged, but isn't documented yet in the README file.

Take a look at the functions here: https://github.com/kleiram/transmission-php/pull/47/files

**Comment by milankragujevic** [comment]
Thank you, you're truly a life saver!

**Comment by Kausheel** [comment]
Actually, I just realized that patch is for reading the download directory, the setDownloadDir function is used internally to set up the object, not for actually assigning a download location.

You can change the download directory with the call outlined in this RPC spec:

https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt#L406

At line 406, there's information about using torrent-set-location()

You can then pass the command to the Transmission RPC through this project by using

$transmission = new Transmission\Transmission();

$response = $transmission->getClient->call('torrent-set-location', array(
    //variables
));

Hope that helps!

**Comment by Kausheel** [comment]
I'm hoping to get a proper move() function merged into this project, link here https://github.com/kleiram/transmission-php/pull/44/files

If it doesn't get merged, you can still just take the code and merge it into your own fork. It'll make it easier for you to move torrents without manually using the RPC.

**Comment by milankragujevic** [comment]
Can I use "download-dir" parameter on method "torrent-add" to add the torrent with a predefined download directory instead of moving it? Can you provide me with the code for that?

**Comment by milankragujevic** [comment]
Actually I found it, method add has support for a save dir location, if I'm not wrong...

https://github.com/kleiram/transmission-php/blob/master/lib/Transmission/Transmission.php#L161

**Comment by Kausheel** [comment]
Yes that looks right!
